### PR TITLE
Removed a cmd level to comply with spec verbatum.

### PR DESCRIPTION
**Pull request by anastasiamac**
Pool and volume commands are now up-to spec.

Pool list is now run as `juju storage list-pools`. Notice that the spec does not explicitly defines format for filter input. I have kept flags for names and types (--name and --type respectively) to ensure that we know what arguments are passed in.

Pool create is now run as `juju storage create-pool <pool name> <provider type, eg loop> <config pairs>` Notice positional arguments.

Volume list is now run as `juju storage list-volumes`. The spec does not define this command. However, it fits the pattern. Since only space-separated names can be used as filter for this command, no flags are defined nor any arguments are expected.

### CODE REVIEW

**Comment by axw** [comment]
LGTM (insofar as it implements the spec ;))

**Comment by wallyworld** [comment]
create-pool needs to have type first and then name
eg
juju storage create-pool ebs "mypool" foo=bar

Also, they want to allow the name to be in " and then have the " removed prior to sending across the wire

**Comment by anastasiamac** [comment]
Actually, it depends where in the spec you look :)

Here is the example that I have implemented from:
    juju storage create-pool ebs fast type=ssd iops=1000
but I can also see a few of
    juju storage create-pool disk "ceph" tags=ceph size=50G

I'll change the order based on your advice.

**Comment by wallyworld** [comment]
TYVVVVVM

**Pull request merged**
